apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: akstestvijays1901
  project: defaultproject
spec:
  blueprintConfig:
    name: aks-cilium
    version: v2
  cloudCredentials: akscreds
  config:
    kind: aksClusterConfig
    metadata:
      name: akstestvijays1901
    spec:
      managedCluster:
        apiVersion: "2022-07-01"
        identity:
          type: SystemAssigned
        location: centralindia
        properties:
          apiServerAccessProfile:
            enablePrivateCluster: true
          dnsPrefix: akstestvijays1901-dns
          kubernetesVersion: 1.27.7
          networkProfile:
            dnsServiceIP: 10.0.0.10
            dockerBridgeCidr: 172.17.0.1/16
            loadBalancerSku: standard
            networkPlugin: azure
            serviceCidr: 10.0.0.0/16
        sku:
          name: Basic
          tier: Free
        type: Microsoft.ContainerService/managedClusters
      nodePools:
      - apiVersion: "2022-07-01"
        location: centralindia
        name: primary
        properties:
          count: 2
          enableAutoScaling: true
          maxCount: 2
          maxPods: 110
          minCount: 2
          mode: System
          orchestratorVersion: 1.27.7
          osType: Linux
          type: VirtualMachineScaleSets
          vmSize: Standard_DS2_v2
        type: Microsoft.ContainerService/managedClusters/agentPools
      resourceGroupName: vijaysaks12042022
  type: aks
