apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: vijayseks24012024
  project: defaultproject
spec:
  blueprintConfig:
    name: minimal
    version: Latest
  cloudCredentials: vijaysrole
  config:
    addons:
    - name: aws-ebs-csi-driver
      version: v1.25.0-eksbuild.1
    managedNodeGroups:
    - amiFamily: AmazonLinux2
      desiredCapacity: 2
      iam:
        withAddonPolicies:
          autoScaler: true
          imageBuilder: true
      instanceTypes:
      - t3.xlarge
      maxSize: 2
      minSize: 2
      name: ngwithdate
      tags:
        email: vijaysamanthapuri@rafay.co
        env: cs-demo1
      volumeSize: 80
      volumeType: gp3
    metadata:
      name: vijayseks24012024
      region: us-west-2
      tags:
        email: vijaysamanthapuri@rafay.co
        env: cs-demo1
      version: "1.25"
    network:
      cni:
        name: aws-cni
    nodeGroups:
    - amiFamily: AmazonLinux2
      desiredCapacity: 2
      iam:
        withAddonPolicies:
          autoScaler: true
          imageBuilder: true
      instancesDistribution:
        instanceTypes:
        - t3.xlarge
      maxSize: 2
      minSize: 2
      name: vijaysselfng24012024
      tags:
        email: vijaysamanthapuri@rafay.co
        env: cs-demo
      volumeSize: 80
      volumeType: gp3
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: true
      nat:
        gateway: Single
      subnets:
        private: {}
        public: {}
  type: aws-eks
