apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: vijays-eks-test1234
  project: defaultproject
spec:
  blueprintConfig:
    name: minimal
    version: 2.2.0
  cloudCredentials: vijaysrole
  config:
    addons:
    - name: aws-ebs-csi-driver
      version: latest
    iam:
      serviceAccounts:
      - metadata:
          name: testsavijays
          namespace: kube-system
        roleOnly: false
        wellKnownPolicies:
          autoScaler: false
          awsLoadBalancerController: true
          certManager: false
          ebsCSIController: false
          efsCSIController: false
          externalDNS: false
          imageBuilder: false
      withOIDC: true
    managedNodeGroups:
    - amiFamily: AmazonLinux2
      desiredCapacity: 2
      iam:
        withAddonPolicies:
          autoScaler: true
          imageBuilder: true
      instanceTypes:
      - t3.xlarge
      maxSize: 2
      minSize: 2
      name: ngwithdate
      privateNetworking: true
      tags:
        email: vijaysamanthapuri@rafay.co
        env: cs-demo1
        myname: vijays
        randomkey: randomvalue
      volumeSize: 80
      volumeType: gp3
    metadata:
      name: vijays-eks-test1234
      region: us-west-2
      tags:
        email: vijaysamanthapuri@rafay.co
        env: cs-demo1
        testkey: testvalue
      version: "1.25"
    network:
      cni:
        name: aws-cni
    nodeGroups:
    - amiFamily: AmazonLinux2
      desiredCapacity: 1
      disableIMDSv1: false
      disablePodIMDS: false
      ebsOptimized: false
      efaEnabled: false
      enableDetailedMonitoring: false
      iam:
        withAddonPolicies:
          albIngress: false
          appMesh: false
          appMeshPreview: false
          autoScaler: true
          certManager: false
          cloudWatch: false
          ebs: false
          efs: false
          externalDNS: false
          fsx: false
          imageBuilder: true
          xRay: false
      instanceType: t3.xlarge
      maxPodsPerNode: 50
      maxSize: 2
      minSize: 1
      name: ng-1
      privateNetworking: true
      subnets:
      - subnet-01191eb45bbc20289
      - subnet-0c2ace7c1bd6f389d
      - subnet-0700983bf90ca0ec6
      tags:
        email: vijaysamanthapuri@rafay.co
        env: cs-demo
      version: "1.25"
      volumeEncrypted: false
      volumeIOPS: 3000
      volumeSize: 80
      volumeThroughput: 125
      volumeType: gp3
    vpc:
      autoAllocateIPv6: false
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      subnets:
        private:
          private-01:
            id: subnet-01191eb45bbc20289
          private-02:
            id: subnet-0c2ace7c1bd6f389d
          private-03:
            id: subnet-0700983bf90ca0ec6
  type: aws-eks
