apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: vijayseks19032024
  project: defaultproject
spec:
  blueprintConfig:
    name: minimal
  cloudCredentials: vijaysrole
  config:
    addons:
    - name: aws-ebs-csi-driver
      version: latest
    iam:
      serviceRoleARN: arn:aws:iam::679196758854:role/vijayseks19032024
      withOIDC: true
    managedNodeGroups:
    - amiFamily: AmazonLinux2
      desiredCapacity: 2
      iam:
        withAddonPolicies:
          autoScaler: true
          imageBuilder: true
      instanceTypes:
      - t3.xlarge
      maxSize: 2
      minSize: 2
      name: ng2
      privateNetworking: true
      tags:
        email: vijaysamanthapuri@rafay.co
        env: cs-demo
      volumeSize: 80
      volumeType: gp3
    metadata:
      name: vijayseks19032024
      region: us-west-2
      tags:
        email: vijaysamanthapuri@rafay.co
        env: cs-demo
      version: "1.25"
    network:
      cni:
        name: aws-cni
        params:
          customCniCrdSpec:
            us-west-2a:
            - securityGroups:
              - sg-0f4021b2dc09124d4
              subnet: subnet-04a4f0d7703a6019d
            us-west-2b:
            - securityGroups:
              - sg-0f4021b2dc09124d4
              subnet: subnet-0ce592c166364df2b
            us-west-2c:
            - securityGroups:
              - sg-0f4021b2dc09124d4
              subnet: subnet-06837762030effed4
    nodeGroups:
    - amiFamily: AmazonLinux2
      desiredCapacity: 3
      iam:
        instanceRoleARN: arn:aws:iam::679196758854:role/vijaysworkerrole
      instanceType: t3.xlarge
      maxPodsPerNode: 50
      maxSize: 4
      minSize: 0
      name: ng-1
      privateNetworking: true
      subnets:
      - subnet-01191eb45bbc20289
      - subnet-0c2ace7c1bd6f389d
      - subnet-0700983bf90ca0ec6
      tags:
        email: vijaysamanthapuri@rafay.co
        env: cs-demo
      version: "1.25"
      volumeEncrypted: false
      volumeSize: 80
      volumeType: gp3
    vpc:
      autoAllocateIPv6: false
      clusterEndpoints:
        privateAccess: true
        publicAccess: true
      subnets:
        private:
          private-01:
            id: subnet-01191eb45bbc20289
          private-02:
            id: subnet-0c2ace7c1bd6f389d
          private-03:
            id: subnet-0700983bf90ca0ec6
  type: aws-eks
